CREATE DATABASE QuanLySanPham;
USE QuanLySanPham;

CREATE TABLE phieuxuat(
soPX INT PRIMARY KEY NOT NULL UNIQUE,
ngayxuat DATE DEFAULT (CURRENT_DATE)
);
create table phieunhap(
soPN INT PRIMARY KEY NOT NULL UNIQUE,
ngaynhap DATE DEFAULT (CURRENT_DATE)
);
CREATE TABLE vattu(
maVTU INT PRIMARY KEY NOT NULL UNIQUE,
tenVTU VARCHAR(100) NOT NULL
);
CREATE TABLE chitietPX (
maVTU INT,
soPX INT,
PRIMARY KEY(maVTU,soPX),
FOREIGN KEY(maVTU) REFERENCES vattu(maVTU),
FOREIGN KEY(soPX) REFERENCES phieuxuat(soPX),
dgXuat VARCHAR(100) NOT NULL,
slXuat INT CHECK(slXuat>0)
);
CREATE TABLE chitietPN (
maVTU INT,
soPN INT,
PRIMARY KEY(maVTU,soPN),
FOREIGN KEY(maVTU) REFERENCES  vattu(maVTU),
FOREIGN KEY(soPN) REFERENCES  phieunhap(soPN),
dgNhap VARCHAR(100) NOT NULL,
slNhap INT CHECK(slNhap>0)
);
CREATE TABLE nhaCC(
maNCC INT PRIMARY KEY NOT NULL UNIQUE,
tenNCC VARCHAR(100) NOT NULL,
diachiNCC VARCHAR (100) NOT NULL
);
CREATE TABLE donDH(
soDH INT PRIMARY KEY,
ngayDH DATE DEFAULT (CURRENT_DATE),
maNCC INT,
FOREIGN KEY (maNCC) REFERENCES nhacc(maNCC)
);
CREATE TABLE chitietDonDH(
maVTU INT,
soDH INT,
PRIMARY KEY (maVTU, soDH),
FOREIGN KEY (maVTU) REFERENCES vattu(maVTU),
FOREIGN KEY (soDH) REFERENCES dondh(soDH)
);
CREATE TABLE sdt(
soDT VARCHAR(20),
maNCC INT,
PRIMARY KEY(soDT,maNCC),
FOREIGN KEY (maNCC) REFERENCES nhaCC(maNCC)
);

